import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync(new URL('../src/components/RealDashboard.tsx', import.meta.url), 'utf8');
const sidebar = readFileSync(new URL('../src/components/AppSidebar.tsx', import.meta.url), 'utf8');
const importView = readFileSync(new URL('../src/components/DataImportView.tsx', import.meta.url), 'utf8');
const root = readFileSync(new URL('../src/main.tsx', import.meta.url), 'utf8');
const sidebarStyles = readFileSync(new URL('../src/integration.css', import.meta.url), 'utf8');
const detailScope = readFileSync(new URL('../src/domain/dashboard/detailScope.ts', import.meta.url), 'utf8');
const summaryStart = source.indexOf('<div className="client-summary">');
const summaryEnd = source.indexOf('</div>', summaryStart);
const actionsStart = source.indexOf('<div className="summary-actions">', summaryStart);
const scopeStart = source.indexOf('<div className="filter-bar client-scope-tabs">', summaryStart);
assert.ok(summaryStart >= 0 && summaryEnd > summaryStart && actionsStart > summaryEnd && scopeStart > actionsStart, 'Ver mais detalhes deve ficar depois do grid e antes da navegação de abas.');
assert.match(source.slice(actionsStart, scopeStart), /Ver mais detalhes/);
assert.match(source, /const \[activeOnly, setActiveOnly\] = useState\(true\)/, 'A carteira deve abrir filtrando clientes ativos.');
assert.match(source, /aria-label="Ativos" checked=\{activeOnly\}/, 'O filtro de ativos deve estar visível e refletir o estado da carteira.');
assert.match(source, /classification: classificationFilter, activeOnly/);
assert.match(importView, /fetch\(apiUrl\('\/api\/clickup\/sync'/, 'A sincronização cadastral deve usar o endpoint servidor ClickUp na base publicada.');
assert.match(importView, /BASE DE CLIENTES — CLICKUP/);
assert.doesNotMatch(importView, /Selecionar base de clientes<input/, 'A base principal não deve depender do upload de planilha.');
const unitPicker = source.slice(source.indexOf("{scope === 'unidades' && <div className=\"module-grid unit-picker\""), source.indexOf('<div className="section-heading">', source.indexOf("{scope === 'unidades' && <div className=\"module-grid unit-picker\"")));
assert.match(unitPicker, /unitAdoptionLabel\(unit\.displayName, unit\.overallScore\)/);
assert.doesNotMatch(unitPicker, /ID\s*['"+]|unit\.unitId\s*!==/);
assert.match(unitPicker, /<Progress score=\{unit\.overallScore\}\/>/);
const moduleExplanationStart = source.indexOf('<strong>Como essa adoção foi calculada?</strong>');
const moduleExplanationEnd = source.indexOf('<div className="indicators-card">', moduleExplanationStart);
assert.ok(moduleExplanationStart >= 0 && moduleExplanationEnd > moduleExplanationStart);
assert.match(source.slice(moduleExplanationStart, moduleExplanationEnd), /<ClassificationGuide score=\{module\.score\}\/>/);
assert.match(sidebar, /Configurações/);
assert.match(sidebar, /Importar dados/);
assert.match(sidebar, /useState\(active === 'settings'\)/);
assert.match(sidebar, /aria-expanded=\{settingsExpanded\}/);
assert.match(sidebar, /setSettingsExpanded\(\(expanded\) => !expanded\)/);
assert.match(sidebar, /active === 'settings' \? 'active' : ''/);
assert.match(sidebar, /aria-label=\{collapsed \? 'Expandir barra lateral' : 'Recolher barra lateral'\}/);
assert.match(sidebar, /title=\{collapsed \? 'Monitoramento de Uso' : undefined\}/);
assert.match(sidebar, /title=\{collapsed \? 'Configurações' : undefined\}/);
assert.match(sidebar, /title=\{collapsed \? 'Importar dados' : undefined\}/);
assert.match(root, /useState\(false\)/);
assert.match(root, /sidebarCollapsed\?\s*' sidebar-collapsed'/);
assert.match(source, /scope=\{selectedModule\.scope\}/);
assert.match(source, /initialScope=\{returnScope\}/);
assert.match(source, /makeDetailScope\(unitId, unitName\)/);
assert.match(source, /loadModule\(selectedClient\.clienteNome, module\.name, scope\.kind === 'unit' \? scope\.unitId : null/);
assert.match(source, /context\.header/);
assert.match(source, /context\.breadcrumb\.map/);
assert.match(detailScope, /find\(\(unit\) => unit\.unitId !== null && String\(unit\.unitId\) === String\(unitId\)\)/);
assert.match(source, /getPortfolioViewState\(loading, customers\.length\)/);
assert.match(source, /<PortfolioSkeleton\/>/);
assert.match(source, /aria-busy="true"/);
assert.match(source, /aria-label="Classificação"/);
assert.match(source, /Nenhum cliente corresponde aos filtros selecionados\./);
assert.match(sidebarStyles, /@media \(prefers-reduced-motion: reduce\)/);
assert.match(sidebarStyles, /\.app\.sidebar-collapsed main \{ margin-left: 72px; \}/);
assert.match(sidebarStyles, /@media \(max-width: 700px\)/);
assert.match(sidebarStyles, /transition: width \.2s ease/);
assert.match(root, /isImportPath\(\)\?'import':'portfolio'/);
assert.match(root, /window\.history\.pushState/);
assert.match(root, /window\.addEventListener\('popstate'/);
assert.match(root, /if\(unitId\)params\.set\('unit_id',unitId\)/);
assert.doesNotMatch(root, /params\.set\('unit_name'/);
assert.equal((root.match(/<DataImportView/g) ?? []).length, 1, 'A rota de importação deve reutilizar uma única instância do componente existente.');
assert.match(source, /Dados processados em \$\{processedDate\}/);
assert.match(source, /indicator\.value === null \|\| indicator\.value === undefined \? 'Dados insuficientes' : String\(indicator\.value\)/);
assert.doesNotMatch(source, /Não totalizado|independentemente da quantidade/);
assert.match(source, /Consolidação entre unidades/);
assert.match(source, /Exibindo \{filteredCustomers\.length\} de \{customers\.length\} clientes/);
assert.match(source, /active-filter-chips/);
assert.match(importView, /formatProcessedDate\(currentStatus\?\.processedAt, true\)/);
assert.doesNotMatch(root, /floating-import/);
assert.match(source, /Monitoramento de Uso – QuarkRH/);
assert.match(source, /Acompanha continuamente a adoção dos módulos contratados pelos clientes do QuarkRH/);
assert.match(source, /Objetivo:<\/strong> transformar dados de utilização em ações proativas/);
assert.match(importView, /api\/import\/progress/);
assert.match(importView, /role="progressbar"/);
assert.match(importView, /Etapa \{progressStep\} de \{stages\.length\}/);
assert.match(importView, /Importação concluída com sucesso\./);
assert.match(importView, /Não foi possível concluir a importação\./);
console.log('Client UI contract tests passed: unit cards, table placement, main navigation, home text and staged import progress/error states');
