import assert from 'node:assert/strict';
import * as XLSX from 'xlsx';
import { parseWorkbook, processFiles, normalizeSignatureDate } from '../scripts/ingestion/core.mjs';
import { formatMrr, formatSignatureDate } from '../src/domain/customer/format.ts';

const csv = 'Task Name,5. MRR (currency),7. DATA DE ASSINATURA (date),9. CATEGORIA RH: (formula)\nCliente Completo,1234.56,"Friday, September 26th 2025",Corporate\nCliente Zero,0,,Standard\nCliente Sem Dados,,,,\n';
const base = parseWorkbook(Buffer.from(csv), 'base-com-metadados.csv');
assert.deepEqual(base.headers.slice(0, 4), ['task_name', '5_mrr_currency', '7_data_de_assinatura_date', '9_categoria_rh_formula']);
const result = await processFiles([{ filename: 'base-com-metadados.csv', content: Buffer.from(csv) }]);
const full = result.customers.find((customer) => customer.clienteNome === 'Cliente Completo');
const zero = result.customers.find((customer) => customer.clienteNome === 'Cliente Zero');
const missing = result.customers.find((customer) => customer.clienteNome === 'Cliente Sem Dados');
assert.equal(full.mrr, 1234.56);
assert.equal(full.signedAt, '2025-09-26');
assert.equal(full.category, 'Corporate');
assert.equal(zero.mrr, 0);
assert.equal(zero.signedAt, null);
assert.equal(zero.category, 'Standard');
assert.equal(missing.mrr, null);
assert.equal(missing.signedAt, null);
assert.equal(missing.category, null);

const sourceHeaders = Array(82).fill(null);
sourceHeaders[2] = 'Task Name'; sourceHeaders[50] = '4. E-MAIL DO RESPONSÁVEL: (email)'; sourceHeaders[51] = '5. MRR (currency)'; sourceHeaders[52] = '6. PLANO: (drop down)'; sourceHeaders[53] = '7. DATA DE ASSINATURA (date)'; sourceHeaders[54] = '8. MODALIDADE DO TREINAMENTO: (drop down)'; sourceHeaders[55] = '9. CATEGORIA RH: (formula)';
const sourceSheet = XLSX.utils.aoa_to_sheet([sourceHeaders]);
const sourceBook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(sourceBook, sourceSheet, 'Clientes');
const positioned = parseWorkbook(XLSX.write(sourceBook, { type: 'buffer', bookType: 'xlsx' }), 'base-com-posicoes-reais.xlsx');
assert.equal(positioned.headers[50], '4_e_mail_do_responsavel_email');
assert.equal(positioned.headers[51], '5_mrr_currency');
assert.equal(positioned.headers[52], '6_plano_drop_down');
assert.equal(positioned.headers[53], '7_data_de_assinatura_date');
assert.equal(positioned.headers[54], '8_modalidade_do_treinamento_drop_down');
assert.equal(positioned.headers[55], '9_categoria_rh_formula');
assert.equal(normalizeSignatureDate('Friday, September 26th 2025'), '2025-09-26');
assert.equal(formatMrr(full.mrr), 'R$ 1.234,56');
assert.equal(formatMrr(zero.mrr), 'R$ 0,00');
assert.equal(formatMrr(null), 'Não informado');
assert.equal(formatSignatureDate(full.signedAt), '26/09/2025');
assert.equal(formatSignatureDate(null), 'Não informado');
console.log('Customer metadata tests passed: actual headers by name, MRR zero/null, signature date and category');
