import assert from 'node:assert/strict';
import { processFiles } from '../scripts/ingestion/core.mjs';
const base = 'Task Name,11. CSM Responsável (users),6. PLANO: (drop down)\nHospital ABC,CSM,QuarkRH Essencial';
const f1 = 'cliente_nome,unidade_id,unidade_nome,qtd_horarios,qtd_jornadas,qtd_solicitacoes,qtd_tratamento_ponto,qtd_colaboradores_registraram_ponto,configuracao_frequencia_ativa\nHospital ABC,1,MATRIZ,2,1,0,0,4,true\nHospital ABC,2,UNIDADE NATAL,3,2,5,1,8,true\nHospital ABC,3,UNIDADE MOSSORO,0,0,0,0,0,false\n';
const f2 = 'cliente_nome,unidade_id,unidade_nome,configuracao_feedback_ativa,qtd_tipos_elogio,qtd_elogios,qtd_feedbacks\nHospital ABC,1,MATRIZ,false,0,0,0\nHospital ABC,2,UNIDADE NATAL,false,0,0,0\nHospital ABC,3,UNIDADE MOSSORO,true,1,1,1';
const result = await processFiles([{ filename: 'clientes.csv', content: Buffer.from(base) }, { filename: 'frequencia.csv', content: Buffer.from(f1) }, { filename: 'feedbacks.csv', content: Buffer.from(f2) }]);
assert.equal(result.customers.length, 1);
const client = result.customers[0];
assert.equal(client.unitCount, 3); assert.equal(client.units.length, 3); assert.equal(client.modules.length, 18);
assert.deepEqual(client.units.map(unit => unit.unitId), ['1','2','3']);
assert.equal(client.units[0].unitName, 'MATRIZ'); assert.equal(client.units[0].modules.length, 18);
assert.equal(client.units[0].modules.find(module => module.name === 'Feedbacks').score, 0);
assert.equal(client.units[2].modules.find(module => module.name === 'Feedbacks').score, 14.5);
assert.equal(client.units[0].modules.find(module => module.name === 'Férias').status, 'dados_insuficientes');
assert.equal(client.units[0].modules.find(module => module.name === 'T&D').contractStatus, 'nao_incluso');
assert.equal(client.units[0].overallScore, 0);
assert.equal(client.modules.find(module => module.name === 'Feedbacks').status, 'calculado');
assert.equal(client.modules.find(module => module.name === 'Feedbacks').score, 14.5);
assert.equal(client.unassignedIndicators.length, 0);
const consolidatedFrequency = client.modules.find(module => module.name === 'Frequência');
const schedules = consolidatedFrequency.consolidationDetails.find(item => item.indicator === 'qtd_horarios');
assert.equal(schedules.rule, 'SOMAR'); assert.equal(schedules.consolidatedValue, 5); assert.equal(schedules.unitValues.length, 3);
assert.equal(schedules.unitValues.find(item => item.unitId === '3').value, 0);

assert.equal(consolidatedFrequency.consolidationDetails.find(item => item.indicator === 'configuracao_frequencia_ativa').consolidatedValue, true);
assert.equal(consolidatedFrequency.consolidationDetails.find(item => item.indicator === 'qtd_colaboradores_registraram_ponto').consolidatedValue, null);
assert.match(consolidatedFrequency.consolidationDetails.find(item => item.indicator === 'qtd_colaboradores_registraram_ponto').reason, /Numeradores e denominadores completos/);
assert.equal(consolidatedFrequency.status, 'dados_insuficientes', 'DP denominator is required even when point counts are available');
assert.notEqual(client.overallScore, null);
assert.notEqual(client.overallScore, (client.units[0].overallScore + client.units[1].overallScore + client.units[2].overallScore) / 3);
assert.equal(result.diagnostics.identifiedUnits, 3); assert.equal(result.diagnostics.clientsWithMultipleUnits, 1);
assert.equal(result.diagnostics.recordsWithoutUnit, 0); assert.equal(result.diagnostics.consolidationMatrix.rows, 122);
assert.ok(result.diagnostics.consolidation.byRule.SOMAR >= 4); assert.ok(result.diagnostics.consolidation.byRule.ANY >= 1);
assert.equal(result.diagnostics.consolidation.byRule.RECALCULAR, 1);
console.log('Multi-unit hierarchy tests passed');
const oneUnitBase = 'Task Name,11. CSM Responsável (users),6. PLANO: (drop down)\nCliente Único,CSM,QuarkRH Essencial';
const oneUnitUsage = 'cliente_nome,unidade_id,unidade_nome,qtd_horarios,qtd_jornadas,qtd_solicitacoes,qtd_tratamento_ponto,qtd_colaboradores_registraram_ponto,configuracao_frequencia_ativa\nCliente Único,9,Sede,0,0,0,0,0,false';
const single = await processFiles([{ filename: 'base.csv', content: Buffer.from(oneUnitBase) }, { filename: 'freq.csv', content: Buffer.from(oneUnitUsage) }]);
assert.equal(single.customers.length, 1); assert.equal(single.customers[0].unitCount, 1); assert.equal(single.customers[0].units[0].unitId, '9'); assert.equal(single.customers[0].units[0].modules.length, 18);
const noIndicators = await processFiles([{ filename: 'base.csv', content: Buffer.from('Task Name,11. CSM Responsável (users),6. PLANO: (drop down)\nSem Uso,CSM,QuarkRH Essencial') }]);
assert.equal(noIndicators.customers[0].unitCount, 0); assert.equal(noIndicators.customers[0].modules.length, 18); assert.ok(noIndicators.customers[0].modules.every(module => module.status === 'dados_insuficientes' || module.status === 'nao_contratado'));
const unknownPlan = await processFiles([{ filename: 'base.csv', content: Buffer.from('Task Name,11. CSM Responsável (users),6. PLANO: (drop down)\nHospital ABC,CSM,Plano Customizado') }, { filename: 'freq.csv', content: Buffer.from(f1) }]);
assert.equal(unknownPlan.customers[0].unitCount, 3); assert.equal(unknownPlan.customers[0].planStatus, 'plano_nao_mapeado'); assert.ok(unknownPlan.customers[0].modules.every(module => module.contractStatus === 'plano_nao_mapeado'));
console.log('Single/no-indicator/unknown-plan unit cases passed');
