import { useMemo, useState } from 'react';
import { calculateAdoptionDashboard, rankCustomersByAdoption, type AnalyticsCustomer, type ModuleAnalytics } from '../domain/dashboard/analytics.ts';
import { formatAdoptionScore } from '../domain/adoption/format.ts';

type Props = { customers: AnalyticsCustomer[]; onOpenCustomer: (customer: AnalyticsCustomer) => void };
type Drilldown = { title: string; customers: AnalyticsCustomer[]; basis: string };
const nameOf = (customer: AnalyticsCustomer) => customer.clienteNome ?? 'Cliente sem nome';
const pct = (value: number | null) => value === null ? 'Dados insuficientes' : formatAdoptionScore(value);

function Metric({ label, value, note }: { label: string; value: string; note: string }) {
  return <div className="metric"><div><span className="metric-label">{label}</span><strong>{value}</strong><small>{note}</small></div></div>;
}

function CustomerRanking({ title, customers, direction, id, onOpen }: { title: string; customers: AnalyticsCustomer[]; direction: 'highest' | 'lowest'; id: string; onOpen: Props['onOpenCustomer'] }) {
  const [journey, setJourney] = useState<'ADOÇÃO' | 'ONBOARDING'>('ADOÇÃO');
  const ranked = useMemo(() => rankCustomersByAdoption(customers, journey, direction), [customers, journey, direction]);
  return <section className="analytics-card"><div className="analytics-card-heading"><div><h2>{title}</h2><p>Jornada selecionada: {journey} · {ranked.length} clientes elegíveis · score zero permanece na lista</p></div></div><div className="analytics-ranking-tabs" role="tablist" aria-label={`Jornada do ranking ${title}`}><button type="button" role="tab" aria-selected={journey === 'ADOÇÃO'} aria-controls={`${id}-panel`} onClick={() => setJourney('ADOÇÃO')}>Adoção</button><button type="button" role="tab" aria-selected={journey === 'ONBOARDING'} aria-controls={`${id}-panel`} onClick={() => setJourney('ONBOARDING')}>Onboarding</button></div><div id={`${id}-panel`} role="tabpanel" aria-label={`${title} · ${journey}`}>{ranked.length === 0 ? <p className="analytics-empty">Nenhum cliente elegível com score calculável na jornada {journey} e nos filtros atuais.</p> : <ol className="analytics-ranking">{ranked.map((customer, index) => <li key={`${nameOf(customer)}-${index}`}><button type="button" onClick={() => onOpen(customer)}><span className="analytics-rank">{index + 1}</span><span className="analytics-customer-name">{nameOf(customer)}</span><span className="analytics-bar-track"><i style={{ width: `${Math.max(0, Math.min(100, customer.overallScore ?? 0))}%` }}/></span><strong>{pct(customer.overallScore)}</strong></button></li>)}</ol>}</div></section>;
}

function ModuleRanking({ title, modules, onSelect }: { title: string; modules: ModuleAnalytics[]; onSelect: (module: ModuleAnalytics, basis: string) => void }) {
  return <section className="analytics-card"><div className="analytics-card-heading"><div><h2>{title}</h2><p>Média por cliente contratado e avaliado; cada cliente tem peso 1</p></div></div>{modules.length === 0 ? <p className="analytics-empty">Dados insuficientes para calcular médias por módulo.</p> : <ol className="analytics-ranking module-ranking">{modules.map((module, index) => <li key={module.name}><button type="button" title={`${module.name}: ${module.contracted} contratantes, ${module.evaluated} avaliados, ${module.insufficient} com dados insuficientes`} onClick={() => onSelect(module, 'Clientes avaliados que compõem a média')}><span className="analytics-rank">{index + 1}</span><span className="analytics-customer-name">{module.name}<small>{module.evaluated} avaliados de {module.contracted} contratantes · {module.insufficient} insuficientes</small></span><span className="analytics-bar-track"><i style={{ width: `${Math.max(0, Math.min(100, module.average ?? 0))}%` }}/></span><strong>{pct(module.average)}</strong></button></li>)}</ol>}</section>;
}

export function AdoptionAnalyticsDashboard({ customers, onOpenCustomer }: Props) {
  const [drilldown, setDrilldown] = useState<Drilldown | null>(null);
  const analytics = useMemo(() => calculateAdoptionDashboard(customers), [customers]);
  const moduleClick = (module: ModuleAnalytics, basis: 'avaliados' | 'insuficientes' | 'baixo') => {
    const customers = basis === 'avaliados' ? module.evaluatedCustomers : basis === 'insuficientes' ? module.insufficientCustomers : module.lowAdoptionCustomers;
    const label = basis === 'avaliados' ? 'avaliados' : basis === 'insuficientes' ? 'com dados insuficientes' : 'com baixa adoção';
    setDrilldown({ title: `${module.name} · ${label}`, customers, basis: basis === 'avaliados' ? 'Score de adoção calculável' : basis === 'insuficientes' ? 'Módulo contratado sem score calculável' : 'Classificação baixa adoção do domínio' });
  };
  if (!customers.length) return <div className="content detail-content"><section className="analytics-empty-state" role="status"><h1>Dashboard de adoção e engajamento</h1><p>Nenhum cliente corresponde aos filtros atuais.</p></section></div>;
  return <div className="content analytics-content"><div className="page-heading"><div><p className="eyebrow">VISÃO ANALÍTICA · DADOS ATUAIS</p><h1>Dashboard de adoção e engajamento</h1><p>Scores consolidados por cliente. Dados insuficientes não são tratados como zero.</p></div><span className="badge success">{analytics.population} clientes na amostra</span></div>
    <div className="metrics analytics-metrics"><Metric label="Adoção média" value={pct(analytics.average)} note={`${analytics.evaluated} clientes com score calculável`}/><Metric label="Clientes avaliados" value={String(analytics.evaluated)} note={`de ${analytics.population} clientes filtrados`}/><Metric label="Baixa adoção" value={String(analytics.lowAdoption)} note="Faixa baixa definida no domínio"/><Metric label="Dados insuficientes" value={String(analytics.insufficient)} note="Sem score geral calculável"/></div>
    {analytics.evaluated === 0 && <p className="analytics-insufficient-note" role="status">A população filtrada não contém scores gerais calculáveis. Gráficos e rankings correspondentes exibem dados insuficientes.</p>}
      <div className="analytics-grid"><CustomerRanking id="top-adoption" title="Top 10 · maior adoção" customers={customers} direction="highest" onOpen={onOpenCustomer}/><CustomerRanking id="bottom-adoption" title="Top 10 · menor adoção" customers={customers} direction="lowest" onOpen={onOpenCustomer}/><ModuleRanking title="Adoção por módulo" modules={analytics.modules.filter((module) => module.contracted > 0)} onSelect={(module) => moduleClick(module, 'avaliados')} /><ModuleRanking title="Módulos com menor adoção" modules={analytics.lowestUseModules} onSelect={(module) => moduleClick(module, 'avaliados')} /><ModuleRanking title="Principais módulos utilizados" modules={analytics.mostUsedModules} onSelect={(module) => moduleClick(module, 'avaliados')} />
      <section className="analytics-card"><div className="analytics-card-heading"><div><h2>Risco por módulo</h2><p>Clientes contratantes classificados como baixa adoção</p></div></div>{analytics.modules.filter((module) => module.contracted > 0).length === 0 ? <p className="analytics-empty">Nenhum módulo contratado nesta população.</p> : <ul className="analytics-risk-list">{analytics.modules.filter((module) => module.contracted > 0).sort((a, b) => b.lowAdoption - a.lowAdoption || a.name.localeCompare(b.name, 'pt-BR')).map((module) => <li key={module.name}><button type="button" onClick={() => moduleClick(module, 'baixo')}><span>{module.name}<small>{module.lowAdoption} baixa adoção · {module.evaluated} avaliados · {module.insufficient} insuficientes</small></span><strong>{module.lowAdoption}</strong></button></li>)}</ul>}</section></div>
    {drilldown && <div className="analytics-drilldown-wrap"><section className="analytics-card analytics-drilldown" aria-label={`Clientes: ${drilldown.title}`}><div className="analytics-card-heading"><div><h2>{drilldown.title}</h2><p>{drilldown.customers.length} clientes · {drilldown.basis}</p></div><button className="secondary-button" type="button" onClick={() => setDrilldown(null)}>Fechar</button></div>{drilldown.customers.length === 0 ? <p className="analytics-empty">Nenhum cliente compõe esta contagem.</p> : <ul>{drilldown.customers.map((customer, index) => { const moduleName = drilldown.title.split(' · ')[0]; const moduleScore = customer.modules?.find((module) => module.name === moduleName)?.score; const value = drilldown.basis === 'Módulo contratado sem score calculável' ? null : moduleScore ?? customer.overallScore; return <li key={`${nameOf(customer)}-${index}`}><button className="analytics-drilldown-customer" type="button" onClick={() => onOpenCustomer(customer)}><span>{nameOf(customer)}</span><strong>{pct(value)}</strong></button></li>; })}</ul>}</section></div>}
    <p className="analytics-footnote">Sem histórico temporal nesta visão. O score de módulo é agregado uma vez por cliente a partir da consolidação já processada, sem ponderação por quantidade de unidades.</p>
  </div>;
}
