import { apiUrl } from '../api';
import React, { useEffect, useState } from 'react';

export function DataStatusPanel() {
  const [status, setStatus] = useState<any>(null);
  useEffect(() => { const refresh = () => fetch(apiUrl('/api/data/status')).then((response) => response.json()).then(setStatus); refresh(); window.addEventListener('quarkrh:data-updated', refresh); return () => window.removeEventListener('quarkrh:data-updated', refresh); }, []);
  const diagnostics = status?.diagnostics;
  const hasImportDiagnostics = diagnostics && Object.keys(diagnostics).some((key) => key !== 'clickupSync');
  const count = (value: unknown) => Array.isArray(value) ? value.length : '—';
  if (!hasImportDiagnostics) return null;
  return <div className="data-status"><strong>Status dos dados</strong><div className="diagnostic-grid"><span>Clientes na base: <b>{diagnostics.clientsInBase}</b></span><span>Clientes únicos por cliente_nome: <b>{diagnostics.uniqueClientsByName}</b></span><span>Relacionados aos indicadores: <b>{diagnostics.relatedClientsToIndicators}</b></span><span>Clientes sem indicadores: <b>{count(diagnostics.clientsWithoutIndicators)}</b></span><span>Módulos encontrados: <b>{diagnostics.modulesFound ?? 0}/{diagnostics.modulesTotal ?? 18}</b></span><span>Indicadores mapeados: <b>{diagnostics.indicatorsMapped ?? 0}</b></span><span>Indicadores ausentes: <b>{diagnostics.indicatorsAbsent ?? 0}</b></span><span>Pendentes de decisão: <b>{diagnostics.indicatorsPendingDecision ?? 0}</b></span><span>Arquivos de indicadores: <b>{diagnostics.indicatorFilesProcessed ?? 0}</b></span></div>{Array.isArray(diagnostics.competencies)&&diagnostics.competencies.length>0&&<div className="import-message warning">Competências analisadas: {diagnostics.competencies.join(', ')}{diagnostics.mixedCompetencies?' · seleção necessária para não misturar períodos.':''}</div>}{Array.isArray(diagnostics.unmappedColumns)&&diagnostics.unmappedColumns.length>0&&<div className="import-message warning">INDICADORES DISPONÍVEIS NÃO MAPEADOS: {diagnostics.unmappedColumns.join(', ')}</div>}{Array.isArray(diagnostics.indicatorNamesNotFound)&&diagnostics.indicatorNamesNotFound.length>0&&<div className="import-message warning">Indicadores não encontrados: {diagnostics.indicatorNamesNotFound.join(', ')}</div>}{Array.isArray(diagnostics.ambiguousClients)&&diagnostics.ambiguousClients.length>0&&<div className="import-message error">Cliente não relacionado por duplicidade de cliente_nome: {diagnostics.ambiguousClients.join(', ')}</div>}{Array.isArray(diagnostics.mapping)&&diagnostics.mapping.map((item:any)=><div className="import-result" key={item.module}><strong>{item.module}</strong><span>{count(item.confirmed)} confirmados · {count(item.absent)} ausentes · {count(item.unmapped)} pendentes</span></div>)}</div>;
}
